apiVersion: v1
kind: Service
metadata:
  name: kibana
  
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - name: ui
    port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    app: kibana
