apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticstack.elasticsearch.service_name }}
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
  - name: db
    port: 9200
    protocol: TCP
    targetPort: db
  selector:
    app: elasticsearch
