apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: elasticsearch-psp
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  # FIXME
  # - elasticsearch-psp
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
# kind: RoleBinding
metadata:
  name: elasticsearch-psp
subjects:
- kind: ServiceAccount
  name: elasticsearch
  namespace: {{ .Values.elasticstack.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-psp
