apiVersion: v1
kind: ConfigMap
metadata:
  name: reporting-queries
  
data:
  queries.json: |
    {
      "list": [
        {
          "name": "resources",
          "query": "{\"bool\":{\"must_not\":[{\"regexp\":{\"spec.containers.resources.limits.cpu\": \".*\"}}]}}"
        }
      ]
    }
