# apiVersion: certmanager.k8s.io/v1alpha1
# kind: Issuer
# metadata:
#   name: letsencrypt-production
#   namespace: reporter-elasticsearch
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: tobias@giantswarm.io
#     privateKeySecretRef:
#       name: letsencrypt-production
#     http01: {}
