---
# Source: reporting/templates/elasticstack/elasticsearch-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: reporting-elasticstack
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
  - name: db
    port: 9200
    protocol: TCP
    targetPort: db
  selector:
    app: elasticsearch
