apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}-reporting-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-reporting-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: {{ .Release.Namespace }}-reporting-agent
  namespace: {{ .Release.Namespace }}
  

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-reporting-agent
rules:
- apiGroups:
  - ""
  resources:
  - daemonsets
  - deployments
  - ingresses
  - namespaces
  - pods
  - replicasets
  - services
  - statefulsets
  verbs:
  - get