apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "agent.name" . }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ template "agent.name" . }}
          restartPolicy: Never
          containers:
          - name: reporting-agent
            image: {{ .Values.agent.image }}:{{ .Values.agent.image_tag }}
            args:
            - bash
            - -c
            - |
              kubectl get --all-namespaces --export --output=json "$RESOURCE_TYPES" | jq -c '.items[]' | while IFS= read -r line; do

                echo "$line" | curl \
                  --insecure --basic --ssl-reqd \
                  --request POST --header 'Content-Type: application/json' \
                  --data @- "$ELASTICSEARCH_INDEX_URL/_doc" \
                    | jq '.'
                echo
              done

            env:
            - name: ELASTICSEARCH_INDEX_URL
              value: http://{{ template "elasticsearch.name" . }}.{{ .Release.Namespace }}.svc:9200/{{ .Values.agent.index }}
            - name: RESOURCE_TYPES
              value: {{ .Values.agent.resource_types }}
