apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kibana.name" . }}
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
      # annotations:
      #   seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      containers:
      - name: kibana
        image: {{ .Values.elasticstack.kibana.image }}:{{ .Values.elasticstack.kibana.image_tag }}
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://{{ template "elasticsearch.name" . }}:9200
          # - name: SERVER_BASEPATH
          #   value: /api/v1/namespaces/kube-system/services/kibana-logging/proxy
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
