apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reporter
  namespace: reporting-agent
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: reporting-agent
          restartPolicy: Never
          containers:
          - name: reporting-agent
            image: quay.io/giantswarm/reporting-agent:1184a230a65709228b458b1c086d1a575b78394c
            args:
            - bash
            - -c
            - |
              kubectl get --all-namespaces --export --output=json "$RESOURCE_TYPES" | jq -c '.items[]' | while IFS= read -r line; do

                echo "$line" | curl \
                  --insecure --basic --ssl-reqd \
                  --request POST --header 'Content-Type: application/json' \
                  --data @- "$ELASTICSEARCH_INDEX_URL/_doc?ttl=3600m" \
                    | jq '.'
                echo
              done

            env:
            - name: ELASTICSEARCH_INDEX_URL
              value: http://elasticsearch.reporting-elasticstack.svc:9200/agent-test1

            # - name: RESOURCE_TYPES
            #   value: clusterrolebindings,clusterroles,componentstatuses,cronjobs,customresourcedefinition,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,podpreset,pods,podsecuritypolicies,podtemplates,replicasets,replicationcontrollers,resourcequotas,rolebindings,roles,serviceaccounts,services,statefulsets,storageclasses
            # - name: RESOURCE_TYPES
            #   value: daemonsets,deployments,ingresses,jobs,namespaces,nodes,pods,replicasets,replicationcontrollers,services,statefulsets
            # - name: RESOURCE_TYPES
            #   value: daemonsets,deployments,ingresses,namespaces,nodes,pods,replicasets,services,statefulsets
            - name: RESOURCE_TYPES
              value: pods
