# apiVersion: v1
# kind: Pod
# metadata:
#   name: toolbox
#   namespace: reporting-agent
# spec:
#   serviceAccount: reporting-agent
#   containers:
#   - image: quay.io/giantswarm/reporting-agent:1184a230a65709228b458b1c086d1a575b78394c
#     command:
#       - "/bin/sh"
#       - "-c"
#       - "while true; do echo '.'; sleep 2; done"
#     imagePullPolicy: IfNotPresent
#     name: toolbox
#     env:
#     - name: ELASTICSEARCH_INDEX_URL_AGENT
#       value: http://elasticsearch.reporting-elasticstack.svc:9200/agent-test1/_doc
#     - name: ELASTICSEARCH_INDEX_URL_PROCESSING
#       value: http://elasticsearch.reporting-elasticstack.svc:9200/processing-test1/_doc
